data:
  datasets:
    CREMA-D:
      path: ../emotion/datasets/CREMA-D/corpus.yaml
  features: wav2vec_c_mean
  remove_groups:
    label:
      keep:
      - anger
      - happiness
      - disgust
      - neutral
aug_data:
  datasets:
    CREMA-D:
      path: datasets/CREMA-D_aug/corpus.yaml
      subset: CREMA-D_spk_emo
      features: datasets/CREMA-D_aug/${aug_data.datasets.CREMA-D.subset}/${data.features}.nc
  remove_groups:
    label:
      keep:
      - anger
      - happiness
      - disgust
      - neutral
model:
  type: null
eval:
  train:
    groups:
      speaker:
        drop: ["1014", "1021", "1026", "1043", "1052", "1056", "1061", "1070", "1084", "1088"]
  test:
    groups:
      speaker:
        keep: ${eval.train.groups.speaker.drop}
